### ISSUE TITLE
Bug in backwards timing

### ISSUE THREAD

**Issue by diakourtis** [tastyigniter/ti-ext-reservation#1]
When a table is booked at 8 and the timeframe is 2 hours is available at 10 and is very correct.
The bug is that the same table is availabe at 7 for reservation, giving only 1 hour timeframe, thus overlapping the 8 oclock time.

**Comment by BreakSecurity** [comment]
Should this be closed? @sampoyigi

**Comment by diakourtis** [comment]
Fixed
