### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation error when auto allocate enabled

### ISSUE THREAD

**Issue by mczernin** [tastyigniter/ti-ext-reservation#14]
**Expected behavior:**
When reserving a table it should be allocated autromatically

**Actual behavior:**
Error: "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '29-0' for key 'reservation_tables_reservation_id_table_id_unique' (SQL: insert into `ti_reservation_tables` (`reservation_id`, `table_id`) values (29, ))"

**Reproduce steps:**
1. Enable auto allocate
2. Reserve a table

**Version:**
3.0.4 beta 27

**Additional Information:**
Reservation Version 2.0.2

**Comment by ryanmitchell** [comment]
Can you provide a full error trace please and ensure its wrapped in `code` so it formats correctl

**Comment by mczernin** [comment]
Unfortunately, I do not get any other errors. System.log stays empty as well…

**Comment by ryanmitchell** [comment]
There should be a full error trace on screen. If not turn debugging on in config/app.php

**Comment by mczernin** [comment]
in my app.php it says
`'debug' => TRUE,`

The only error i get is this:
<img width="605" alt="Screenshot 2021-05-05 at 19 45 05" src="https://user-images.githubusercontent.com/5412072/117185699-6726bd80-adda-11eb-8f89-90e63844bb3f.png">

**Comment by ryanmitchell** [comment]
Ok. Can you share screens of your table set up then so we can replicate your environment. I’m not seeing the issue on my dev site so it must be happening due to your table setup.

**Comment by mczernin** [comment]
Thank you, Ryan! My table setup is as follows:

<img width="721" alt="Screenshot 2021-05-05 at 19 55 00" src="https://user-images.githubusercontent.com/5412072/117187047-c89b5c00-addb-11eb-95f6-59d22ea85622.png">

**Comment by ryanmitchell** [comment]
Hmm seems to be working ok on my side.
Is this a clean install or an upgrade? Something definitely seems wrong on your install.

**Comment by mczernin** [comment]
Ho weird. Yes it was a clean install using the setup wizard…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sampoyigi** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please reopen if it still occurs.
