### ISSUE TITLE
 Tables are not getting assigned automatically and shown on other locations

### ISSUE THREAD

**Issue by huwayyy** [tastyigniter/ti-ext-reservation#16]
**Expected behavior:**
1. A table assigned to location 1 should only be usable in reservations of location 1.

2. tables assigned to new added location should get automatically joined when autoallocation is enabled.

3. Reservations with X persons should only join tables with X >= min. persons.

**Actual behavior:**
1. All tables are usable in any location, even if tables are only assigned to one location

2. Its does not join any table for a new created location. For the first location of demo content it works well.

3. Table 1 has min. persons 5, reservations with 2 persons autojoin to table 1

**Reproduce steps:**
1. 
- created new locations "test" and "test2"
- created one or more tables only assigned to location "test"
- created reservation and choose as location "test2"
- now i can also choose tables from location "test" 

2.
- Created new location "test"
- Activated "Automatically Allocate Tables" in Settings tab
- Created new tables and assign to location "test" with setting joinable "true"
- Created new reservation in frontend for location "test" 
- Go to Reservations in Adminpanel and no table was joined automatically

3.
- Look at actual behavior

**Version:**
3.0.4 Beta 28

**Additional Information:**
I alway did a clean install with setup script.
Already tried on different Webservers (OpenLitespeed, nginx, apache2) and PHP Versions (7.2, 7.3, 7.4)
No errors in Logfiles

**Comment by sampoyigi** [comment]
To get around the first issue, you'll need to create a separate admin account restricted to each location, that way only tables assigned to their location are available to choose from.

Other issues have been patched! Please confirm they work for you.

**Comment by huwayyy** [comment]
Thank you for your work. 

i tried your patches and they dont work for me. Tables aren't getting assigned for Location1 and Location2 now... 
i also tried a fresh installation with your patches.

**Comment by sampoyigi** [comment]
Fixed e135cff29a02a3f8b11b075e74d5811d291fa329 & https://github.com/tastyigniter/TastyIgniter/commit/4f66e9cca76439eaa6f53a5dce018a390ac270b8

**Comment by sampoyigi** [comment]
Closing, but please reopen if it still occurs.
