### ISSUE TITLE
Reservation Stay Time not working as it should

### ISSUE THREAD

**Issue by Rye6006UK** [tastyigniter/ti-ext-reservation#19]
**Expected behavior:**
I have only 2 tables, both reserved for 7PM & I have a Reservation Stay Time of 60 minutes.
When a customer tries to reserve a table, they should only be able to select 6PM or earlier as per the Reservation Stay Time

**Actual behavior:**
I have only 2 tables, both reserved for 7PM & I have a Reservation Stay Time of 60 minutes.
When a customer tries to reserve a table before 7PM, they are able to select all the way up to 6:45PM, meaning they would have a reservation for only 15 minutes, which is not inline with the Reservation Stay Time of 60 minutes.

**Reproduce steps:**
Set Reservation Time Interval = 15, Reservation Lead Time = 60, and Reservation Stay Time = 60.
![image](https://user-images.githubusercontent.com/12779209/126667493-57631d42-917f-4cbd-a131-b0e235f49a40.png)

Remove all but tables 1 & 2 from the system.
![image](https://user-images.githubusercontent.com/12779209/126667433-cf87f001-c7b6-4135-92b7-3b06e0edb45e.png)

Make 2 reservations for the exact same date and time, filling the available tables.
![image](https://user-images.githubusercontent.com/12779209/126667552-9bd1afcf-d7bc-4931-b2e0-fd5bcb802d98.png)

Try to add a further reservation for 15 minutes before the other 2, which shouldn't be allowed as the 3rd reservation cannot have a full 60min Reservation Stay Time
![image](https://user-images.githubusercontent.com/12779209/126665435-a3d6ba06-16c4-4a38-ad35-69404ff30211.png)

**Version:**
TastyIgniter v3.0.5

**Additional Information:**
None

**Comment by sampoyigi** [comment]
The issue here is the timeslots are generated based on the set Reservation Time Interval and not the Stay Time. With stay time set to 60 mins, all timeslots between 7pm and 8pm will be blocked.
