### ISSUE TITLE
[Bug]: No use of locale in displaying date in reservation-listing

### ISSUE THREAD

**Issue by git-gnulf** [tastyigniter/ti-ext-reservation#22]
### What happened?

In Sales -> Reservations -> ListView the shown date of the reservations is always in english. If I use my own language (german) I see english named month- and daynames.

My TastyIgniter-Version is 3.0.8

### What did you expect to happen?

If I switch my language I want to see the month- and daynames in the words of the current language. In my example in german. 

### Version

Other (please detail)

### What browser are you seeing the problem on?

Firefox

**Comment by ryanmitchell** [comment]
This should be fixed by https://github.com/tastyigniter/TastyIgniter/commit/7dad2c1a1e25eb5a5417c1a1f149f7d4e4161c19
