### ISSUE TITLE
[Bug]: Spooky behaviour when editing E-Mail-Template

### ISSUE THREAD

**Issue by git-gnulf** [tastyigniter/ti-ext-reservation#24]
### What happened?

When editing an email-template I noticed some spooky behaviour:
- I cant click the tabs markdown / plaintext. The view didnt change. 
- If I change the scope from "global variables" to for example "reservation-variables", the variables didnt change. Beginning I see $site_name and $site_logo and after change I see both again.
- if I hit the save Button, nothing happens. The form was not saved.
- if I want to go to the system > logs and hit on the system-link, nothing happens. No menu expand.
- if I want to hit any of the menu (Marketing, Users, Restaurant, and so on), none of the menu opened.
- suddenly I m logged out within a few minutes.

I checked it on two computers.

My TI-Version is 3.1.2

### What did you expect to happen?

- When I click the tabs markdown / plaintext I expect, that the view changes and I can edit the one or the other.
- If I change the scope from "global variables" to "reservation-variables", I expect that the variables change and I was shown the variables for this scope. 
- if I hit the save Button, I expect, that the form was saved.
- if I want to go to the system > logs and hit on the system-link, I expect that the menu expand and I can click at the log-link- 
- if I want to hit any of the menu (Marketing, Users, Restaurant, and so on), I expect the that the menu opened.

### Version

Other (please detail)

### What browser are you seeing the problem on?

Firefox

### Relevant log output

```shell
No output in system-logs

In Browser-Console I found:
Uncaught SyntaxError: nothing to repeat 71522847877b57957cc59fbc0e8ab35b-1635759012.js:885:243580
```

**Comment by diverds1992** [comment]
make sure that'enableAssetCombiner' => FALSE in config/system.php,

if you cant find the record then add it manualy

**Comment by ryanmitchell** [comment]
Do you mean `'enableAssetCombiner' => TRUE` ? The error you pasted shows the assets are combined

**Comment by diverds1992** [comment]
I had the same strange behaviour of the menu when i updated broadcaster events and setting to false fixed this behaviour

**Comment by ryanmitchell** [comment]
Yep @sampoyigi something in broadcaster events is causing issues with asset combiner

**Comment by git-gnulf** [comment]
> make sure that'enableAssetCombiner' => FALSE in config/system.php,
Yes. This works for me - Thank you :)

**Comment by sampoyigi** [comment]
> Yep @sampoyigi something in broadcaster events is causing issues with asset combiner

I'll have a look

**Comment by sampoyigi** [comment]
@diverds1992 @ryanmitchell Ok, I'm unable to reproduce the problem here. On the latest release, switching tabs and editing email templates works fine for me. Is a complete error log for the broadcast extension error available?

**Comment by ryanmitchell** [comment]
I would say the changes to the asset combiner will resolve this

**Comment by sampoyigi** [comment]
Not reproducible in the latest release. Please reopen this issue if it still occurs, with a set of reproducible steps.
