### ISSUE TITLE
[Bug]: missing language support for the dates in reservation-listing

### ISSUE THREAD

**Issue by git-gnulf** [tastyigniter/ti-ext-reservation#25]
### What happened?

In Sales -> Reservation -> Listing View is a column date. In a german environment the date contains the english names for days and month.
![2021-11-10_19-11](https://user-images.githubusercontent.com/85353101/141182456-0bf45cf1-e10f-47b8-a4db-cfedb9b5c4d4.png)

### What did you expect to happen?

In my german environment I expect to see the german day- and monthnames.

To reproduce follow this steps:
Have an other language than english (i.e. german), setup in the language-interface in field system::lang.php.date_format a format with day- and monthnames ( (D) d. F Y ).

Let a customer create a new reservation with a month like (December, January, March).
Go to Admin Sales -> Reservations -> List View and have a look at the date column.
In an german environment you should see Dezember, Januar, März and the daynames should be Montag, Dienstag, Mittwoch and so on.

my TI-version 3.1.2

### Version

Other (please detail)

### What browser are you seeing the problem on?

Firefox

### Relevant log output

```shell
Log Files are empty
```

**Comment by ryanmitchell** [comment]
@sampoyigi the simplest fix for this would be to use Carbon::setLocale() when we set the local in the service provider or app provider. However Carbon themselves advise against using it in the docs...

> Previously there was Carbon::setLocale that set globally the locale. But as for our other static setters, we highly discourage you to use it. It breaks the principle of isolation because the configuration will apply for every class that uses Carbon.

The other option would be to change every date output to use formatLocalized() or ->locale('xxx')->format()

**Comment by sampoyigi** [comment]
Already fixed here https://github.com/tastyigniter/TastyIgniter/commit/7dad2c1a1e25eb5a5417c1a1f149f7d4e4161c19 please confirm

**Comment by ryanmitchell** [comment]
@sampoyigi ah you're ahead of the game 🤣

**Comment by git-gnulf** [comment]
Ah, this sounds good :)
Thank you!
