### ISSUE TITLE
[Bug]: missing language support for the dates in e-mails

### ISSUE THREAD

**Issue by git-gnulf** [tastyigniter/ti-ext-reservation#26]
### What happened?

In a german environment: If the customers get an email when reserve a table, they see the day they booked the table not in german format but in english format.
![2021-11-10_21-21](https://user-images.githubusercontent.com/85353101/141187618-a6a06ef6-0daa-4429-9d84-780ca80d76a1.png)

And also the waiters / the location. 
![2021-11-10_21-19](https://user-images.githubusercontent.com/85353101/141187329-4512dc63-48af-4777-9581-81d433593a0f.png)

### What did you expect to happen?

In a german environment I expect to see the day- and monthnames in german.

Steps to reproduce:
- have an other language than english
- setup in language - interface the field system::lang.php.date_format_long with an format that displays day- and monthnames (l, d. F Y)
- let a customer create a new reservation and have a look at the e-mail the customer and the e-mail the location received.  

My TI-Version: 3.1.2

### Version

Other (please detail)

### What browser are you seeing the problem on?

Firefox

### Relevant log output

```shell
No LogOutput
```

**Comment by ryanmitchell** [comment]
This would be closed if we apply the same approach I suggest in https://github.com/tastyigniter/ti-ext-reservation/issues/25

**Comment by ryanmitchell** [comment]
Should be fixed by https://github.com/tastyigniter/TastyIgniter/commit/7dad2c1a1e25eb5a5417c1a1f149f7d4e4161c19

**Comment by git-gnulf** [comment]
But this solves only the date/time locale format in the admin-listing not in the e-mails. Right?

I assume, there were two an other lines to modify.
In `/app/admin/models/Reservations_model.php` line 429 and 430 should changed to:

```
$data['reservation_time'] = Carbon::createFromTimeString($model->reserve_time)
->isoFormat(lang('system::lang.moment.time_format'));
```

`$data['reservation_date'] = $model->reserve_date->isoFormat(lang('system::lang.moment.date_format'));`

I hope, it is not only a hack ;)

What do you think?

**Comment by ryanmitchell** [comment]
Seems right to me, open a PR !
