### ISSUE TITLE
[Bug]: A reserved table is not blocked for manual reservation

### ISSUE THREAD

**Issue by git-gnulf** [tastyigniter/ti-ext-reservation#31]
### What happened?

A customer booked a table via the public TI-webinterface. The system reserved a table for this customer at the chosen date and time. For example "Table 5" at 20. June at 10:00 am. 

A waiter reserves a table via the admin-interface (> Sales > Reservations > +New-Button). At random the date and time are the same like the customer above (20. June at 10:00 am.), and at next random the waiter chose the same table ("Table 5"). 
This new reservation was saved. 
No warning - no error raises.

### What did you expect to happen?

If a waiter reserve a table via admin-interface I expect the system checks if a table was still reserved and raises an error or warning. And not only for exact the same time but for times overlapping. For example:

A Customer booked a table at 10.00 - and the system reserves him a table, this table was blocked at 10:00 and also at 10:30 or 11:00 - depending what retention time was configured.

### Version

3.5.x

### What browser are you seeing the problem on?

Firefox

**Comment by git-gnulf** [comment]
@sampoyigi and @ryanmitchell Is this bug really completed? I tried it today again and I m still able to book the same table via the admin-interface at the same time like an other customer has booked it via the website. Could you be so kind as to have again a look at this point? Or is this behavior intended? 

I ve installed a fresh tastyigniter 3.5.5
Would it be better to raise a new issue for the same?

**Comment by sampoyigi** [comment]
The way this works is you leave the tables selection blank when creating the reservation so the tables are automatically assigned avoiding double booking

**Comment by git-gnulf** [comment]
Ok, thanks - that is a possible way. 
Hmmm ... but, what if a customer (or the waiter) has a wish for a special table?
Then the waiter will select the table by hand and cant look at quick if the table is free at this time.
