### ISSUE TITLE
[Bug]: trubles on filter reservation status

### ISSUE THREAD

**Issue by git-gnulf** [tastyigniter/ti-ext-reservation#35]
### What happened?

I go to admin-interface > sales > reservations > dropdown "view all status" select a status (for example "new"). Now I see all reservations with status new. So far so good. 

Now I want to see all reservations again. I drop down the view-status-menue and select the option "select all/none". I see for one second all options are marked. Next the page reload and I see only a blank page. No menu, no data, nothing - pure white.
The url is /admin/reservations.

Reloading the page didnt work. I ve to call the /admin page. Then I see the dashboard and can go back to reservations. Here I cant switch the selected status via dropdown-menu view-status. Nearly every time I get a white blank page. I can go back with browsers back-button. The new selected status is saved. But the filtered entries are not updated. It is a bit confusing.

That I can hit the red cross and can reset the filter I ve noticed after 5 minutes playing around with this error while writing this report ;) I suggested the red cross is only for deleting my manually insert id, guest number, table name, etc. and not for resetting all the filters.

### What did you expect to happen?

I expect that I can deselect my selection of status and no blank page was load ;)

### Version

3.5.x

### What browser are you seeing the problem on?

Firefox

### Relevant log output

```shell
Symfony\Component\ErrorHandler\Error\FatalError: Uncaught Igniter\Flame\Exception\ApplicationException: Ajax handler [list_filter::onSubmit] is not found.
in /var/www/httpdocs/app/main/classes/MainController.php:373 

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error
in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ','12'' at line 1 in /var/www/httpdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82
```

**Comment by sampoyigi** [comment]
Fixed https://github.com/tastyigniter/TastyIgniter/commit/de8ec05062adf2368639c6147f1c406d14650617
