### ISSUE TITLE
[Bug]: List Setup - Reservations - Changes not saved

### ISSUE THREAD

**Issue by git-gnulf** [tastyigniter/ti-ext-reservation#36]
### What happened?

I go to sales > reservations > setup and chose which columns I want to see. Some options I disable, some I enable. I click save. So far so fine. If I logout from admin-interface and login again the changes in list-setup are gone. 

### What did you expect to happen?

I expect that the options are saved. Even if I logout from admin-interface.

### Version

3.5.x

### What browser are you seeing the problem on?

Firefox

**Comment by sampoyigi** [comment]
Your changes are stored in the user session which is cleared/regenerated when you login/logout
