### ISSUE TITLE
Tables not auto joining when making a reservation

### ISSUE THREAD

**Issue by shannonsavage** [tastyigniter/ti-ext-reservation#8]
**Expected behavior:**
When a guest makes a reservation through the front end, the appropriate number of tables should be allocated to the booking based on the number of guests. (eg reservation for 12 pax, TI has tables of 5x tables with max capacity of 4 pax setup, it should allocate 3x tables to that booking). Tables are enabled to be auto-joinable. 

**Actual behavior:**
The front end will say "No table found for the specified number of guests at the selected location." Reducing the number of PAX will still show this error until you reach 4 pax. 

**Reproduce steps:**
1) Goto the reservation front end screen, selecting 12 people. The page will auto refresh, with the time field now being disabled, with the rest of the time options being disabled also. Pressing the find table button results in the error "No table found for the specified number of guests at the selected location."

![Screen Shot 2021-01-11 at 9 34 23 pm](https://user-images.githubusercontent.com/28548652/104170177-d1df7200-5454-11eb-9bc3-2f6b353270fa.png)

**Version:**
v3.0.4-beta.25.2

**Additional Information:**
Reservation Extension version: 0.1.0

**Comment by sampoyigi** [comment]
@shannonsavage Can you help us test the linked PR #10 to be sure it resolves the issue?

**Comment by shannonsavage** [comment]
> @shannonsavage Can you help us test the linked PR #10 to be sure it resolves the issue?

Heya @sampoyigi @ryanmitchell , looks to be all good! Tested by reducing the table sizes to max capacity of 4. Made a reservation as it allocated 3x tables to the reservation as expected.

The only other thing I noticed was in the timeslot selector when on the first step of the reservation front end, the first reservation time has increased by 1 hour (first available time is 18:30), restaurant opening time is 17:30. Despite no bookings at all for 17:30 on that date. Reverting the code makes 17:30 available.

**Comment by ryanmitchell** [comment]
Are you just applying the changes to those code lines or changing the entire file? 

Nothing in the code changed should be affecting the lead time, so I wonder if its something else that has been changed since your install. What version of TI and the reservation extension are you currently using?

**Comment by shannonsavage** [comment]
@ryanmitchell I overwrote BookingManager.php with what was contained in PR #10 .
Running TI v3.0.4-beta.25.2 with Reservation Extension version: 0.1.0

**Comment by ryanmitchell** [comment]
I *think* it may be due to you not being on 26.2 then - @sampoyigi can you see anything in the changes that would affect lead times?

**Comment by sampoyigi** [comment]
Yea must be related to the installed version. Nothing from the PR would affect lead times.

**Comment by rasollo** [comment]
I am also having this problem on a clean install.
