### ISSUE TITLE
Unable to select restaurant when creating reservation in admin panel

### ISSUE THREAD

**Issue by shannonsavage** [tastyigniter/ti-ext-reservation#9]
**Expected behavior:**
When creating a reservation via the admin panel, the restaurant dropdown box should allow you to select the location to assign to the reservation. 

**Actual behavior:**
The restaurant dropdown box is disabled and a location is unable to be selected. The HTML markup has the disabled attribute assigned to it. 

**Reproduce steps:**
1) Login to Admin Panel > Sales > Reservations > Create
2) Restaurant Selector is disabled. 

![image](https://user-images.githubusercontent.com/28548652/104171073-318a4d00-5456-11eb-962c-c6450c990a49.png)

![image](https://user-images.githubusercontent.com/28548652/104171173-5b437400-5456-11eb-965f-929e2aae6e4b.png)

**Version:**
v3.0.4-beta.25.2

**Additional Information:**
Reservation Extension version: 0.1.0

**Comment by sampoyigi** [comment]
That's a feature for the version you are using. We've now enabled the location dropdown field in the latest version beta.26.
